language: go
sudo: false

matrix:
  include:
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: tip

env:
  - TEST_DIR=computer-vision
  - TEST_DIR=emotion
  - TEST_DIR=face
  - TEST_DIR=spell-check
